# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a14bbf11b3e41082fb4d7de0a31882dfdd3e6933dfd0378a627c8c6fef0816475347b841b88e26c1886d628fa4637b52537f8f024c25d31b8c404c0b684ad26

test:
  secret_key_base: b10bcecd2a072177e39a0a02f7e6054ba8a0f81b591883078f79eb12f9b73b46b684ba79f9f5ad67cf600e88d5a37a8cf677879c29c0e9014bf79c0b8e1deb9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
